Do not override files during decrypt and check for seemingly succesful decrypt, fixes #1

diff --git a/pdfnopw b/pdfnopw
--- a/pdfnopw
+++ b/pdfnopw
@@ -10,8 +10,20 @@ then
   exit 1
 fi
 
+if [ -f "$FILE.decrypt" ]
+then
+  echo "$FILE.decrypt already exists; will not override"
+  exit 1
+fi
+
 #decrypt
 qpdf --password=$PASSWORD --decrypt $FILE "$FILE.decrypt"
+
+if [ ! -f "$FILE.decrypt" ]
+then
+  echo "Something went wrong decrypting; aborting"
+  exit 1
+fi
 
 #mv into bak
 mv "$FILE" "$FILE.bak"
